module.exports = [
  {
    title: "Luxury Apartment",
    description: "A spacious apartment in the city center.",
    price: 250000,
    location: "New York",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Beach House",
    description: "A beautiful house near the beach.",
    price: 500000,
    location: "California",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Mountain Cabin",
    description: "A cozy cabin in the mountains.",
    price: 300000,
    location: "Colorado",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Penthouse Suite",
    description: "A luxurious penthouse with city views.",
    price: 1000000,
    location: "Miami",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Country Estate",
    description: "A peaceful estate in the countryside.",
    price: 800000,
    location: "Texas",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Modern Loft",
    description: "A modern loft in the heart of the city.",
    price: 400000,
    location: "San Francisco",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Lakefront Cottage",
    description: "A charming cottage by the lake.",
    price: 350000,
    location: "Maine",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Suburban Home",
    description: "A spacious home in the suburbs.",
    price: 250000,
    location: "Illinois",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Villa in the Hills",
    description: "A luxurious villa with scenic views.",
    price: 950000,
    location: "Los Angeles",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "City Studio",
    description: "A compact studio apartment in the city.",
    price: 150000,
    location: "Boston",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Urban Loft",
    description: "An industrial-style loft in a downtown location.",
    price: 450000,
    location: "Chicago",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Charming Bungalow",
    description: "A quaint bungalow near the park.",
    price: 200000,
    location: "Florida",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Luxury Condo",
    description: "A high-end condo in a prime location.",
    price: 700000,
    location: "Seattle",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Historic Mansion",
    description: "A historic mansion with modern amenities.",
    price: 2000000,
    location: "Philadelphia",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Eco-Friendly House",
    description: "A sustainable, eco-friendly home.",
    price: 450000,
    location: "Oregon",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Contemporary House",
    description: "A stylish house with sleek design.",
    price: 600000,
    location: "Austin",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Coastal Retreat",
    description: "A retreat by the sea with breathtaking views.",
    price: 800000,
    location: "Hawaii",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Minimalist Apartment",
    description: "A minimalist apartment in a quiet area.",
    price: 350000,
    location: "Denver",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Rural Farmhouse",
    description: "A large farmhouse in a rural area.",
    price: 600000,
    location: "Kentucky",
    image: "https://via.placeholder.com/150",
  },
  {
    title: "Urban Penthouse",
    description: "A penthouse apartment with stunning views.",
    price: 1500000,
    location: "New York",
    image: "https://via.placeholder.com/150",
  },
];
